# Generated by Django 5.1.5 on 2025-01-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('ingredients', models.TextField()),
                ('cooking_time', models.IntegerField()),
                ('difficulty', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
