# Generated by Django 5.1.5 on 2025-01-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(default='recipes_no_picture.jpg', upload_to='recipes'),
        ),
    ]
